"""
Generator for a GPU rental "deploy bundle" — produces all the files a user
needs to spin up a vast.ai or RunPod instance and resume their seed recovery
on GPU (with --enable-opencl).

Output: a dict {filename: content_str} that the route handler packs into a
ZIP archive.
"""
from __future__ import annotations

import json
import shlex
from datetime import datetime, timezone
from typing import Dict, List, Optional

# Default Docker base image — works on both vast.ai and RunPod and ships with
# NVIDIA OpenCL drivers usable by pyopencl.
DEFAULT_IMAGE = "nvidia/cuda:12.3.2-runtime-ubuntu22.04"

BTCRECOVER_REPO = "https://github.com/3rdIteration/btcrecover.git"


# ---------- seedrecover argv reconstruction (CPU+GPU) ----------
def _build_seedrecover_argv(cfg: dict, enable_opencl: bool = True) -> List[str]:
    """
    Same logic as backend's build_seedrecover_command but produces a flat
    argv list (no python prefix) ready to be embedded in a shell script.
    """
    argv = [
        "python3", "-u", "seedrecover.py",
        "--no-pause", "--no-gui", "--disablesecuritywarnings",
    ]
    seed_length = int(cfg.get("seed_length", 12))
    known = cfg.get("known_words") or [""] * seed_length
    mnemonic = " ".join((w.strip() or "?") for w in known[:seed_length])
    argv += ["--mnemonic", mnemonic]
    argv += ["--mnemonic-length", str(seed_length)]
    argv += ["--language", cfg.get("language", "en")]
    argv += ["--wallet-type", cfg.get("wallet_type") or "electrum2"]

    if cfg.get("address"):
        argv += ["--addrs", cfg["address"]]
        argv += ["--addr-limit", str(int(cfg.get("addr_limit", 10)))]
    if cfg.get("mpk"):
        argv += ["--mpk", cfg["mpk"]]
    if cfg.get("wallet_file_path"):
        argv += ["--wallet", cfg["wallet_file_path"]]
    if cfg.get("passphrase_enabled") and cfg.get("passphrase"):
        argv += ["--passphrase-arg", cfg["passphrase"]]

    threads = int(cfg.get("threads", 2))
    argv += ["--threads", str(threads)]
    typos = int(cfg.get("typos", 0))
    if typos > 0:
        argv += ["--big-typos", str(typos)]
    if enable_opencl:
        argv += ["--enable-opencl"]
    return argv


def _shell_quote_argv(argv: List[str]) -> str:
    return " ".join(shlex.quote(a) for a in argv)


# ---------- File generators ----------
def _gen_dockerfile(image: str) -> str:
    return (
f"""# Auto-generated by seed-recovery-dashboard — GPU recovery image
# Base: {image}
FROM {image}

ENV DEBIAN_FRONTEND=noninteractive \\
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \\
        python3 python3-pip python3-dev git \\
        build-essential ocl-icd-libopencl1 ocl-icd-opencl-dev clinfo \\
        ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

# btcrecover (3rdIteration fork) + pyopencl for GPU search
RUN git clone --depth=1 {BTCRECOVER_REPO} /opt/btcrecover \\
    && cd /opt/btcrecover \\
    && pip3 install --no-cache-dir -r requirements.txt \\
    && pip3 install --no-cache-dir pyopencl

WORKDIR /opt/btcrecover

# Job artifacts are mounted/copied here at runtime
COPY candlist.txt /opt/btcrecover/candlist.txt
COPY config.json  /opt/btcrecover/config.json
COPY run.sh       /opt/btcrecover/run.sh
RUN chmod +x /opt/btcrecover/run.sh

CMD ["/opt/btcrecover/run.sh"]
""")


def _gen_run_sh(argv: List[str], job_label: Optional[str]) -> str:
    cmd = _shell_quote_argv(argv)
    label = job_label or "seed-recovery"
    return (
f"""#!/usr/bin/env bash
# Auto-generated runner — executes seedrecover.py inside the GPU container.
set -euo pipefail

echo "==> Job label  : {label}"
echo "==> Started at : $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "==> OpenCL info:"
clinfo -l || true

cd /opt/btcrecover
echo "==> Running    : {cmd}"
echo
exec {cmd}
""")


def _gpu_cli_name(friendly: Optional[str]) -> str:
    """
    Extract a vast.ai-CLI-compatible GPU model name from a friendly label.
    Examples:
        'vast.ai · RTX 3090'  -> 'RTX_3090'
        'RunPod · A100 40GB'  -> 'A100'
        'RunPod · RTX A4000'  -> 'RTX_A4000'
        None / unknown        -> 'RTX_3090'
    """
    if not friendly:
        return "RTX_3090"
    # Drop provider prefix
    parts = friendly.split("·")
    tail = parts[-1].strip() if parts else friendly.strip()
    # Drop VRAM suffix like ' 40GB' / ' 80GB'
    import re as _re
    tail = _re.sub(r"\s+\d+GB$", "", tail)
    return tail.replace(" ", "_") or "RTX_3090"


def _gen_vastai_deploy_sh(image: str, gpu_friendly: Optional[str], max_dph: Optional[float]) -> str:
    gpu_cli = _gpu_cli_name(gpu_friendly)
    gpu_display = gpu_friendly or gpu_cli
    max_dph = max_dph if max_dph is not None else 0.50
    bundle_note = (
        "# Upload the bundle:\n"
        "#   tar czf bundle.tgz Dockerfile run.sh candlist.txt config.json\n"
        "#   vastai copy bundle.tgz $INSTANCE_ID:/root/\n"
        "#   vastai ssh $INSTANCE_ID 'cd /root && tar xzf bundle.tgz && docker build -t seedrec . && docker run --gpus all -it seedrec'\n"
    )
    return (
f"""#!/usr/bin/env bash
# Auto-generated — provision a vast.ai instance for GPU seed recovery.
# Requires: pip install vastai && vastai set api-key <YOUR_KEY>
#
# Target GPU : {gpu_display}  (vastai filter: {gpu_cli})
# Max $/h    : {max_dph}
# Docs       : https://vast.ai/docs/cli/commands
set -euo pipefail

# 1. Find the cheapest reliable {gpu_cli} offer
echo "==> Searching offers for {gpu_cli} ..."
vastai search offers \\
    'reliability > 0.95 num_gpus=1 gpu_name={gpu_cli} dph_total<{max_dph} cuda_vers>=11.0 inet_down>50 inet_up>20' \\
    -o 'dph_total' | head -n 20

echo
read -p "Enter the OFFER ID from the list above: " OFFER_ID

# 2. Create instance with the base image (we'll build the recovery image on the box)
echo "==> Creating instance ..."
INSTANCE_ID=$(vastai create instance "$OFFER_ID" \\
    --image {image} \\
    --disk 10 \\
    --label seed-recovery \\
    --onstart-cmd 'env | grep _ >> /etc/environment; apt-get update && apt-get install -y docker.io tar' \\
    | awk -F\\' '/new contract/ {{print $2}}')

echo "==> INSTANCE_ID=$INSTANCE_ID — wait ~60s for it to boot, then:"
echo
{bundle_note}
""")


def _gen_runpod_md(image: str, gpu_name: Optional[str]) -> str:
    gpu_name = gpu_name or "RTX A6000"
    return (
f"""# RunPod deploy steps

1. **Create a Pod** with these settings:
   - **GPU**: {gpu_name}
   - **Image**: `{image}` (use the "Custom Image" option)
   - **Disk**: 10 GB volume + 10 GB container disk
   - **Expose**: TCP port `22` (SSH) is enough

2. **Upload this bundle** via the RunPod web terminal or `scp`:
   ```bash
   tar czf bundle.tgz Dockerfile run.sh candlist.txt config.json
   scp -P <pod_ssh_port> bundle.tgz root@<pod_ip>:/root/
   ```

3. **Connect to the pod** (`Connect → SSH over exposed TCP`) and run:
   ```bash
   cd /root && tar xzf bundle.tgz
   docker build -t seedrec .
   docker run --gpus all -it --rm seedrec
   ```

4. **Watch the output**. When done, `docker cp` any result files back to
   your local machine, then **stop the pod** to stop billing.

> ⚠️ Reminder: anyone with access to the rented box can see the config you
> upload. For maximum safety, blank the `passphrase` field in `config.json`
> and supply it via `--passphrase-arg` only at the prompt.
""")


def _gen_readme(provider: str, gpu_name: str, eta_human: Optional[str], local_eta_human: Optional[str], cost_local_eur: Optional[float], cost_rental_eur: Optional[float]) -> str:
    saving = ""
    if cost_local_eur is not None and cost_rental_eur is not None:
        saving = f"\nExpected saving: **€{cost_local_eur:.2f} (local) → €{cost_rental_eur:.2f} (GPU)** = €{cost_local_eur - cost_rental_eur:.2f}\n"
    return (
f"""# Seed Recovery — GPU Deploy Bundle

Generated: `{datetime.now(timezone.utc).isoformat()}`
Provider:  **{provider}**
GPU:       **{gpu_name}**
Expected ETA on GPU: **{eta_human or 'N/A'}** (vs **{local_eta_human or 'N/A'}** local)
{saving}

## Files in this bundle

| file              | purpose                                                |
|-------------------|--------------------------------------------------------|
| `Dockerfile`      | nvidia/cuda + btcrecover + pyopencl image              |
| `run.sh`          | runner that executes seedrecover.py --enable-opencl    |
| `config.json`     | snapshot of the seed-recovery configuration            |
| `candlist.txt`    | candidate wordlist (BIP39 / Electrum / custom)         |
| `{('vastai-deploy.sh' if provider == 'vastai' else 'runpod-deploy.md')}` | provider-specific instructions     |
| `verify.txt`      | the recovery target (address / mpk) for double-check   |

## Quick start ({provider})

{('See `vastai-deploy.sh` for the full CLI flow.' if provider == 'vastai' else 'See `runpod-deploy.md` for step-by-step instructions.')}

## Safety notes

- This bundle contains **only public information** (target address, known seed
  positions, candidate wordlist). It does NOT contain the recovered seed.
- If you set a `passphrase`, it has been **redacted** in `config.json`.
  Pass it on the rented box with `--passphrase-arg` only.
- The rented GPU box can in principle read anything you upload. Use a fresh
  provider account, destroy the instance the moment recovery completes.
- For ultimate safety, run on air-gapped hardware.

## Cleanup

When recovery finishes:
- copy any output files back via `vastai copy` / `scp`
- destroy the instance (`vastai destroy instance <id>` or "Terminate" on RunPod)
- verify the bill, rotate the API key

Good luck.
""")


# ---------- Public entry point ----------
def generate_bundle(
    cfg: dict,
    wordlist_text: str,
    *,
    provider: str = "vastai",
    gpu_name: Optional[str] = None,
    max_dph: Optional[float] = None,
    image: str = DEFAULT_IMAGE,
    eta_human: Optional[str] = None,
    local_eta_human: Optional[str] = None,
    cost_local_eur: Optional[float] = None,
    cost_rental_eur: Optional[float] = None,
    job_label: Optional[str] = None,
) -> Dict[str, str]:
    """Return {filename: content} for the deploy bundle."""
    if provider not in ("vastai", "runpod"):
        raise ValueError(f"Unsupported provider '{provider}'")

    # Redact passphrase before snapshotting
    safe_cfg = dict(cfg or {})
    if safe_cfg.get("passphrase"):
        safe_cfg["passphrase"] = "***REDACTED — supply on the rented box***"

    argv = _build_seedrecover_argv(safe_cfg, enable_opencl=True)

    files: Dict[str, str] = {
        "Dockerfile": _gen_dockerfile(image),
        "run.sh": _gen_run_sh(argv, job_label),
        "config.json": json.dumps(safe_cfg, indent=2, sort_keys=True, default=str),
        "candlist.txt": wordlist_text or "",
        "verify.txt": (
            f"address: {safe_cfg.get('address') or '-'}\n"
            f"mpk:     {safe_cfg.get('mpk') or '-'}\n"
            f"wallet:  {safe_cfg.get('wallet_file_path') or '-'}\n"
        ),
        "README.md": _gen_readme(
            provider=provider,
            gpu_name=gpu_name or "GPU",
            eta_human=eta_human,
            local_eta_human=local_eta_human,
            cost_local_eur=cost_local_eur,
            cost_rental_eur=cost_rental_eur,
        ),
    }
    if provider == "vastai":
        files["vastai-deploy.sh"] = _gen_vastai_deploy_sh(image, gpu_name, max_dph)
    else:
        files["runpod-deploy.md"] = _gen_runpod_md(image, gpu_name)

    return files
